### ISSUE TITLE
Test start date shows as "Invalid Date" until the test finishes

### ISSUE THREAD

**Issue by stevenvergenz** [adlnet-archive/grail-issue-tracker#1]
On the list of active tests.

**Comment by creighton** [comment]
<img width="1187" alt="screen shot 2016-08-04 at 2 23 07 pm" src="https://cloud.githubusercontent.com/assets/1065054/17414077/f8cc6a82-5a51-11e6-867b-4596bef0f713.png">

**Comment by kylemoran** [comment]
https://github.com/adlnet/lrs-test-frontend/commit/a5a40e9bc52d23678e4fd3342fcfe8a3c998ef09
