### ISSUE TITLE
An LRS's About API's version property can only have values of ".9", ".95", "1.0", "1.0.0", or ""1.0." + X" with (Communication 2.8.s5.b1.b1) 

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#12]
AssertionError: expected [ Array(6) ] to include '0.9'

However the LRS returns 

```
"version": [
    "0.9",
    "0.95",
    "1.0.2"
  ]
```

**Comment by fugu13** [comment]
The requirement is also wrong. There's nothing nonconformant about an LRS that supports 1.0.3 (for example) that also supports, say, 1.1.7, or 23.6.91, or 1.0.4-barbarella (that last is an example of the use of dev tags for prerelease versions, which is supported by the versioning standard we follow).

Also, 1.0 is not a legal value. That value is only ever legal in the x-experience-api-version header.

**Comment by kylemoran** [comment]
fixed in 49276f06a09843a7eb9fd3122b014c3a8e0c9853
