### ISSUE TITLE
(failed) should fail when "StatementRef" points to a voiding statement 

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#17]
This is not a requirement. It's not even a recommendation. 

In fact, I think we discussed this on a call a while back and agreed that LRSs shouldn't be required to check this.

**Comment by fugu13** [comment]
Yeah, definitely not a requirement. The only requirement is that an LRS must not actually void voiding statements -- but it's allowed to accept statements voiding voiding statements (or reject them, if it checks), it just can't act as if the voiding statement worked. And it can certainly accept (MUST, even) statement refs that aren't in voiding statements to voiding statements.

**Comment by ljwolford** [comment]
Discussed this on the conformance call earlier in the week, test has been adjusted to send a statement that voids a voiding statement and checks to make sure the voiding statement was not voided.
