### ISSUE TITLE
top LRS configuration is always used

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#18]
I added Request Bin as an LRS configuration to try and get the details of the request being made, but the test suite always uses the top LRS configuration.

**Comment by rchadwic** [comment]
Hey, I can't reproduce this. If I create 2 configurations for a product, one which has the proper URL and one that does not, the tests pass and or fail as expected, and the GUI displays the expected values. Can you give more info on how to recreate?

**Comment by garemoko** [comment]
I too can no longer replicate. I'm pretty sure it's not pebkac in this case, but who knows...
