### ISSUE TITLE
should succeed when attachment is raw data and request content-type is "multipart/mixed" 

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#19]
For this test, Watershed is recording the error message "Header section has more than 10240 bytes (maybe it is not properly terminated)". 

What's the full request being sent?

**Comment by rchadwic** [comment]
Until we can get better data moved up to the web layer, you can troubleshoot this by running the tests yourself from the console. Check out the https://github.com/adlnet/lrs-conformance-test-suite

**Comment by rchadwic** [comment]
humm... The headers seem normal for this request.

```
POST /xapi/statements HTTP/1.1
Content-Type: multipart/mixed; boundary=-------314159265358979323846
X-Experience-API-Version: 1.0.1
Authorization: Basic dG9tOjEyMzQ=
host: 10.100.10.92
content-length: 17116
Connection: close

---------314159265358979323846
Content-Type: application/json

{"actor":{"objectType":"Agent","mbox":"mailto:sample.agent@example.com","name":"Sample Agent"},"verb":{"id":"http://adlnet.gov/expapi/verbs/answered","display":{"en-US":"answered"}},"object":{"id":"http://www.example.com/tincan/activities/multipart","objectType":"Activity","definition":{"name":{"en-US":"Multi Part Activity"},"description":{"en-US":"Multi Part Activity Description"}}},"timestamp":"2014-07-11T13:51:03.971Z","attachments":[{"usageType":"http://example.com/attachment-usage/test","display":{"en-US":"A test attachment"},"contentType":"image/jpeg","length":27,"sha2":"4e37e243f7a18e0af9ab83bf9adc0f7d03654b60c34d9658ce6ce967d8239287","description":{"en-US":"A test attachment (description)"}}]}
---------314159265358979323846
Content-Disposition: attachment; filename="riptide_software.jpg"
Content-Type: image/jpeg
Content-Transfer-Encoding: binary
X-Experience-API-Hash: 4e37e243f7a18e0af9ab83bf9adc0f7d03654b60c34d9658ce6ce967d8239287
```

then a bunch of binary.

**Comment by garemoko** [comment]
When you say "then a bunch of binary" - is there an empty line break before the binary?

**Comment by garemoko** [comment]
Also is the closing boundary correct?

**Comment by rchadwic** [comment]
Yeah, closing boundary is correct.  
`---------314159265358979323846--`

Yeah, there appears to be a newline

```
...
X-Experience-API-Hash: 4e37e243f7a18e0af9ab83bf9adc0f7d03654b60c34d9658ce6ce967d8239287

Éê`ë·¤ì=*||K²Õ¢½Ù5R·3î]Å-Þ¶«Ümw#*nR 
...
```

**Comment by garemoko** [comment]
hm. Could you email the full request to andrew.downes@watershedlrs.com and I'll try to replicate in postman. Thanks!

**Comment by garemoko** [comment]
Having reviewed the file I'm currently thinking this is a Watershed issue rather than a test suite issue. I'll log a ticket with our development team and wait for them to confirm that before i close this though.

**Comment by garemoko** [comment]
Closing for now. Will re-open if I decide it's a test suite issue

**Comment by bscSCORM** [comment]
@garemoko you might have been running into the `CRLF` vs just `CR` issue I just found: https://github.com/adlnet/grail-issue-tracker/issues/67

**Comment by garemoko** [comment]
@bscSCORM seems likely. Thanks!
