### ISSUE TITLE
An LRS rejects with error code 400 Bad Request, a Request which does not use a "X-Experience-API-Version" header name to any API except the About API 

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#20]
Tests 2-4 under this section are all coming without an authentication header.

**Comment by ljwolford** [comment]
Seems to have been fixed in an earlier commit though only the statements endpoint is covered currently. More tests for the other endpoints will be added.

**Comment by garemoko** [comment]
Appears to be fixed.
