### ISSUE TITLE
Error: Missing: no update status code using PUT

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#21]
(failed) An LRS's Statement API rejects with error code 409 Conflict any Statement with the "statementID" parameter equal to a Statement in the LRS already **Implicit** (Communication 2.1.1.s2.b2)

(failed) should return 409 or 204 when statement ID already exists on PUT 

I don't understand the error message for this test. Watershed has no record of any error for this test and behaves appropriately when I test PUT a statement that already exists using Postman.

**Comment by kylemoran** [comment]
https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Communication.md#211-put-statements

An LRS MUST NOT make any modifications to its state based on receiving a Statement with a statementId that it already has a Statement for. Whether it responds with 409 Conflict or 204 No Content, it MUST NOT modify the Statement or any other Object.

**Comment by garemoko** [comment]
To clarify, the error message here is in the title "Error: Missing: no update status code using PUT"

**Comment by ljwolford** [comment]
I will update the error message to make more sense. Haven't come across this during my testing, are you still having this issue @garemoko ?

**Comment by garemoko** [comment]
@ljwolford I haven't re-run the test suite since I put all these in. I'm planning to hold off re-running it until they are all marked as resolved (or have questions like this) - is that going to hold you up?

**Comment by ljwolford** [comment]
No, it's fine. I'll close it then and once all of the other issues are handled and you re-run, we can reopen it if needed (along with any others).
