### ISSUE TITLE
stream ended unexpectantly

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#22]
A "statements" property is an Array of Statements (Data 2.5.s2.table1.row1)

should return StatementResult with statements as array using GET with "attachments" 

This test gets the error 'stream ended unexpectantly' - is the closing boundary present in the request?

**Comment by rchadwic** [comment]
Humm it does seem to include the boundary correctly. Take a look at line 3248 in non_templating.js

**Comment by garemoko** [comment]
Going to hold off looking at this until the improvements in displaying what's send and received mentioned in https://github.com/adlnet/grail-issue-tracker/issues/29#issuecomment-242745309 lands.
