### ISSUE TITLE
should only return voiding statement when using "until" 

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#23]
What does this requirement mean? What specifically is being tested? Voiding statements can be included in requests that don't use until, in fact they are more likely to be included.

**Comment by fugu13** [comment]
Yeah, that doesn't line up with the spec at all. It would be good to test for receiving voiding statements back under a number of situations, but many won't involve until at all.

**Comment by ljwolford** [comment]
It was included in a group of tests that should have been concentrating on statements targeting a voided statement. The voiding statement mentioned in that test name was just being reused for an 'until' test case. This case and a few others can be written more generically and will be addressed with the reorg.

**Comment by garemoko** [comment]
I didn't come across this in my last test so assume this was indeed fixed as part of the re-org.
