### ISSUE TITLE
Missing specifcation link

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#24]
An LRS rejects with error code 400 Bad Request, a GET Request which uses Attachments, has a "Content-Type" header with value "application/json", and has the "attachments" filter attribute set to "true" (4.1.11.a)

**Comment by cr8onski** [comment]
Link added: https://github.com/adlnet/lrs-conformance-test-suite/commit/e5c89c5a4cc0c56939186c9b809baab16d71f938
