### ISSUE TITLE
Requirement makes no sense

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#25]
An LRS rejects with error code 400 Bad Request, a GET Request which uses Attachments, has a "Content-Type" header with value "application/json", and has the "attachments" filter attribute set to "true" (4.1.11.a) 

Why would a GET request have a content type? What does "which uses Attachments" mean in this context? Which spec requirement is being referenced? How did you actually implement this?

**Comment by garemoko** [comment]
Most of this also applies to 

> An LRS's Statement API will reject a GET request having the "attachment" parameter set to "false" and the Content-Type field in the header set to anything but "application/json" (7.2.3.d, 7.2.3.e)

**Comment by fugu13** [comment]
Yeah, the whole GET requests with content-types or content-lengths thing that got sprinkled in the requirements doesn't make any sense. I also made a note that "which uses attachments" is far too general, in the aha stuff.

**Comment by ljwolford** [comment]
This was discussed in the conformance group earlier this week and we determined it could be stricken.
