### ISSUE TITLE
Expected response status code to be 400 got 403

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#26]
An LRS rejects with error code 400 Bad Request, a Request whose "authority" is a Group and consists of non-O-Auth Agents (Data 2.4.9.s3.b1)
Error: Expected response status code to be 400 got 403

403 is a reasonable response to an unknown authority being set.

**Comment by garemoko** [comment]
Also applies to the authority tests in 

> An "actor" property with "objectType" as "Agent" uses one of the following properties: "mbox", "mbox_sha1sum", "openid", "account"

It's perfectly valid to return 403 here since the authority is unknown

**Comment by fugu13** [comment]
I haven't looked at the test yet, but the comment about "also applies" confuses me -- why would there by authority tests in a section about the actor property?

**Comment by fugu13** [comment]
As for the 403 response code, I think there are some ways to construct an authority where a 400 is definitely the more acceptable, and a 403 is a little weird for any of them -- since the LRS is generally supposed to overwrite authorities, it'd be very weird to accept-and-overwrite authorities that are legally formatted with a generic credential yet 403 authorities that are not legally formatted, as an auth model.

All that said, I don't care very much; the spec gives a lot of permissiveness on permissions, so tentatively before I look into the test I'd say a 403 is fine here.

**Comment by garemoko** [comment]
> why would there by authority tests in a section about the actor property?

I think theres a few sections that are badly titled. Really this section is testing usage of the agent object in various places it can occur. I can see that it makes sense to group these together. 

> As for the 403 response code, I think there are some ways to construct an authority where a 400 is definitely the more acceptable, and a 403 is a little weird for any of them 

What's happening here is that the authority is bad for two reasons: 
1. It doesn't match the authority associated with the credentials used (and therefore is forbidden) 
2. It's badly formatted. 

The order of those checks is what's causing this to get a 403 and I don't think we should (or do) require the LRS to validate the format of credentials it already knows are wrong. 

> I'd say a 403 is fine here

:+1:

**Comment by fugu13** [comment]
There's no requirement in the spec that the authority coming in match the credentials used. The requirement is that if the LRS sets the authority it must match the credentials used; if it chooses to trust the credentials to write their own authority, then the authority would often not match the credentials used (as that's the whole point of trusting the credentials). A 403 doesn't really make sense any way you slice it (though I'm still fine with it).

**Comment by garemoko** [comment]
>  it chooses to trust the credentials to write their own authority
> That's the key point - by default the credentials generated in Watershed's UI are not trusted to write their own authority. 

I guess the solution is to use an elevated set of credentials that does have permission to set the authority for the test suite.

**Comment by garemoko** [comment]
Closing because we came to a solution back in August.
