### ISSUE TITLE
Cancel Button on Advanced Tests Screen Doesn't Work

### ISSUE THREAD

**Issue by oconnetf** [adlnet-archive/grail-issue-tracker#31]
If I click "Cancel" on this screen, nothing happens.

<img width="687" alt="grail advanced tests" src="https://cloud.githubusercontent.com/assets/1247486/18139278/59566946-6f76-11e6-85c8-c26a87940abb.png">

**Comment by rchadwic** [comment]
Right - all the forms just use ":back" for those links. I'll try to think of a better way to handle that.

**Comment by garemoko** [comment]
This works now.
