### ISSUE TITLE
Test Hanging with No Feedback

### ISSUE THREAD

**Issue by oconnetf** [adlnet-archive/grail-issue-tracker#32]
I can't tell whether the test ever times out, but I'm more than 8 hours deep, at this point.

<img width="960" alt="grail hang" src="https://cloud.githubusercontent.com/assets/1247486/18152731/c2591758-6fbd-11e6-89fe-b12a4ee8218a.png">

**Comment by creighton** [comment]
Do you mind cancelling the test? We can then look at the logging to help us track this down.

**Comment by oconnetf** [comment]
Canceled!

**Comment by creighton** [comment]
awesome, thank you. we'll look into it

**Comment by creighton** [comment]
Would you mind if we rerun the test with the configuration you used?

**Comment by oconnetf** [comment]
Not at all. Do you want to fire it off, or do you want me to?

**Comment by rchadwic** [comment]
Nope, I'll take it. I'd like to watch the console.

**Comment by cr8onski** [comment]
There was a bug in using the 'X-Experience-API-Consistent-Through' header such that when the con-thru header was not present or not a number caused the test to run indefinitely.

**Comment by oconnetf** [comment]
So does grail-alpha run against master or development?

I'm still getting a hung test, but now at least I can see the logs upon cancellation.

**Comment by cr8onski** [comment]
Yes, grail-alpha runs against master.
