### ISSUE TITLE
Confusing Email Notification on Canceled Test

### ISSUE THREAD

**Issue by oconnetf** [adlnet-archive/grail-issue-tracker#33]
When I canceled a test, I received an email with this subject: "Your LRS conformance test is complete."

Clicking the "View test results" link in the email leads to a "Test not found" page.

**Comment by creighton** [comment]
Looks like there's some weird issue in that one case you had.. we're looking into it.

Normally that email link would take you to your cancelled log.

**Comment by oconnetf** [comment]
![f358c01bc56a238e86f60092a21bb852](https://cloud.githubusercontent.com/assets/1247486/18177254/03115482-703f-11e6-8ec5-9975320fedb0.jpg)

**Comment by rchadwic** [comment]
So, the log failed to persist because it had grown too large. Not sure exactly what to do in that case - maybe trim the log so that the record of the test at least would get into the DB.
