### ISSUE TITLE
Log Download File Has .json Extension But Appears to Be Text

### ISSUE THREAD

**Issue by oconnetf** [adlnet-archive/grail-issue-tracker#34]
It would be nice to be able to download test results as a CSV or have some way to share them easily without a user management requirement.

**Comment by rchadwic** [comment]
Yeah, so, let me explain a bit about the workflow. When you get a set of results that indicate conformance - IE: you ran all tests and passed them, a button will light that says "make public". This sets the results as the public claim, listing your product in the "conformant products index". In this state, anonymous users can view the results on the same "test status" page (with the control options disabled of course). Additionally, once you've associated a passing test run with the product, you'll have an option to download a certificate. This cert is a summary of the logs, signed with the ADL conformance signing key. Anyone can review the that summary. It just lists some data about the endpoint, authtype, date and time, XAPI version and test suite version. Anyone can validate the signed payload themselves, or upload the cert to the web service. In the last case, they will be given a link to the full log (if the owner has not deleted it).

**Comment by rchadwic** [comment]
But yeah, we should expand the "download log" link to include more than just the HTTP logs, but all the data on the "Test status" page in addition to the HTTP traffic.

**Comment by oconnetf** [comment]
Oh! Well, I hadn't noticed that under Manage Test Results. That's still better than the thing I didn't see at first.

Maybe I should change the issue to "Log Download File Has .json Extension But Appears to Be Text".

**Comment by rchadwic** [comment]
Ah. Yeah that's a bug then.

**Comment by rchadwic** [comment]
fixed in # 13453fb
