### ISSUE TITLE
Test Doesn't Complete

### ISSUE THREAD

**Issue by oconnetf** [adlnet-archive/grail-issue-tracker#36]
As described in #35, even with the latest commits, we get a scenario where we can reliably fail to get a complete test run.

**Comment by rchadwic** [comment]
Can you try running this from the console runner? I think we've fixed this in the test suite repo, but won't push to the server  for a several days.

**Comment by oconnetf** [comment]
Probably not till next week at the earliest. :(

**Comment by oconnetf** [comment]
So ... better? The status says "finished", but it shows 99% complete, and I have no way of really knowing how many tests were supposed to have run. Could be a math error?

<img width="1189" alt="finished" src="https://cloud.githubusercontent.com/assets/1247486/19258052/48d4840c-8f3a-11e6-9dcb-30528dd1183a.png">

**Comment by rchadwic** [comment]
Yeah this is surely just a rounding error somewhere. Under the hood, we do know how many test are expected to run for a given set of options, so that progressbar should be right (ish)
