### ISSUE TITLE
No Error Message Provided When Test Doesn't Complete

### ISSUE THREAD

**Issue by oconnetf** [adlnet-archive/grail-issue-tracker#37]
As mentioned in #35, if a test doesn't complete for unknown reasons, there is nothing suggesting an error state, and there's also no error message available to the test runner.

At a minimum, this ought to be visible as an unexpected state (from the suite's standpoint). It'd be understandable if the actual error message itself were only logged internally, though.

**Comment by rchadwic** [comment]
Agreed - we need some way to detect this... really, if in any case the state is "finished" but the percent complete is less than 100, this should be an error. However, merely being in this state is sort of a bug - it should not be possible.

**Comment by creighton** [comment]
OBE - if this is still a problem, please submit a new issue
