### ISSUE TITLE
Download Just Errors

### ISSUE THREAD

**Issue by oconnetf** [adlnet-archive/grail-issue-tracker#38]
Right now, I have to download a huge log in its entirety even if 90% of tests are passing.

It be nice to have an opportunity just to download the error log.

**Comment by rchadwic** [comment]
Hummm that we can probably do. I think we do a bit of processing before download anyway....

**Comment by cr8onski** [comment]
in development branch, can select option from the console to have only errors in log, commit 49e44c1

**Comment by rchadwic** [comment]
fixed in commit 4cc5c96e1ccebd32
