### ISSUE TITLE
Prefer Machine-readable (or at Least Standard) Log Format

### ISSUE THREAD

**Issue by oconnetf** [adlnet-archive/grail-issue-tracker#40]
We've already opened https://github.com/adlnet/grail-issue-tracker/issues/38 as a nice-to-have, but it would be nice if the downloadable log from the test runner could be made available as JSON (which is what is output by default from the test suite itself -- https://github.com/adlnet/lrs-conformance-test-suite).

**Comment by rchadwic** [comment]
added in commit 4cc5c96e1ccebd32
