### ISSUE TITLE
No cancel button when editing a product

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#5]
![image](https://cloud.githubusercontent.com/assets/1363163/17937509/43662a38-6a1a-11e6-96a0-b72c07df02b6.png)

**Comment by garemoko** [comment]
Also when editing configuration.

**Comment by garemoko** [comment]
And when configuring advanced tests

**Comment by rchadwic** [comment]
Added "cancel" link to all forms in #9846172
