### ISSUE TITLE
Some tests do not provide the request/response

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#51]
The request/response is vital for confirming failed tests. The following two tests do not include this:

`An LRS's Activity Profile Resource, rejects a POST request if the document is found and either doucment is not a valid JSON Object`

`An LRS's must reject, with 400 Bad Request, a POST request to the Acitvity Profile Resource which contains name/value pairs with invalid JSON and the Content-Type header is "application/json"`

Also note "doucment" and "Acitvity" in the test names.

**Comment by garemoko** [comment]
Also under HEAD Request Implementation Requirements, the two tests 'should succeed GET about with no body' and 'should succeed HEAD about with no body' don't include the requests.

**Comment by garemoko** [comment]
Also several tests under Alternate Request Syntax Requirements:

* An LRS rejects a new Request in the same way for violating rules of this document as it would a normal Request
* Any LRS Resource that accepts a POST request can accept a POST request with a single query string parameter named "method" on that request
* An LRS will reject any request sending content which does not have a form parameter with the name of "content"
* An LRS will treat the content of the form parameter named "content" as a UTF-8 String
* An LRS will reject a new Request with a form parameter named "content" if "content" is found to be binary data with error code 400 Bad Request 
* An LRS must parse the body of a Cross Origin Request and construct a new Request from it with the type of Request being the same as the value of the "method" parameter 
* An LRS will map form parameters from the body of the Cross Origin Request to the similarly named HTTP Headers in the new Request

**Comment by garemoko** [comment]
Also under the Document Resource Requirements the tests titled 'Should accept POST to X with document 1' and 'Should accept POST to X with document true'.

**Comment by rchadwic** [comment]
fixed in https://github.com/rchadwic/supertest/commit/2a2346bc82d3c7233d363c265c5bf3b1be6ee5b2

You'll need to update modules in the install. 

npm remove supertest
npm remove super-request
npm install
