### ISSUE TITLE
Shouldn't we log underlying test issues at https://github.com/adlnet/lrs-conformance-test-suite

### ISSUE THREAD

**Issue by bscSCORM** [adlnet-archive/grail-issue-tracker#66]
I'm confused about the proper use of this tracker, I'd expect issues with the tests themselves to be logged at: https://github.com/adlnet/lrs-conformance-test-suite, but I see some here. Can we add a Readme.md in one place or another laying out the correct practice?

**Comment by cr8onski** [comment]
You are welcome to use either. We monitor both.
