### ISSUE TITLE
Multipart must include CRLF in separator

### ISSUE THREAD

**Issue by bscSCORM** [adlnet-archive/grail-issue-tracker#67]
I'm seeing this on Windows, in case that impacts the test. I won't include the whole request here since it's large, but from the test `should succeed when attachment is raw data and request content-type is \"multipart/mixed\"` , per RFC 1341 the part separator needs to include `CRLF`, which would be encoded here as `\r\n`

```
The term CRLF, in this document, refers to the  sequence  of
            the  two  ASCII  characters CR (13) and LF (10) which, taken
            together, in this order, denote a  line  break  in  RFC  822
            mail.
```

Note, the test is only sending the `CR`, not `CRLF`. Therefore the expected response for this test, and any other test that sends an attachment with only `CR` should be `400`, bad request.

> }}]}\r---------314159265358979323846\rContent-Disposition:

**Comment by cr8onski** [comment]
Thanks, it looks like those line endings got changed.  I will put them back.  and the .gitattributes file should have kept them straight.  Well let us know if it happens again.

**Comment by bscSCORM** [comment]
@cr8onski you could have the tests that do attachments scan the attachment data they're sending for "CRLF" and throw a "this test is broken, line endings reset again see commit ... blah" if it finds it, might be worth it to make the issue more obvious if it crops up again.
