### ISSUE TITLE
Adopters Site: Conformant LRS listing card subtitle

### ISSUE THREAD

**Issue by milt** [adlnet-archive/grail-issue-tracker#69]
On the adopter site, in the listing of conformant LRSs, the contact name is displayed directly under the name of the LRS product like so:
![image](https://cloud.githubusercontent.com/assets/782173/24974912/d3b2620a-1f91-11e7-8f51-dfec92217314.png)

As much as I'd like to take credit for *all* the hard work that went into making our LRS, this should probably be the company name instead, no?

**Comment by kylemoran** [comment]
https://github.com/adlnet/adopterRegistry/pull/4
