### ISSUE TITLE
lrstest/adopters site: expired cert

### ISSUE THREAD

**Issue by milt** [adlnet-archive/grail-issue-tracker#72]
Hey, you all probably know about this, but the cert on both the test and adopters site is expired.

![image](https://cloud.githubusercontent.com/assets/782173/25347466/077fd530-28e9-11e7-9267-58a943169a02.png)

**Comment by creighton** [comment]
Yep thanks for the heads up. We're working on it. Hopefully it'll be fixed in the next hour or so.

**Comment by creighton** [comment]
Ok it should be fixed.
