### ISSUE TITLE
Ability to specify patch version being used

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#8]
It looks like the test suite is requiring version 1.0.1 of the spec to be used, whereas either it should accept any patch version (especially including 1.0.2), or it should allow the test runner to specify the patch version. Really it shouldn't matter which patch version an LRS is using. 

Tests include: 
- (failed) An LRS's About API's version property contains at least one string of "1.0.1" (Communication 2.8.s5.b1.b1) 
- An LRS MUST set the X-Experience-API-Version header to the latest patch version (Communication 3.3.s3.b2) should respond with header "version" set to "1.0.3"

**Comment by garemoko** [comment]
Arguably this is a bug as well as a feature request since it's causing tests to fail. Especially since it expects the LRS to list 1.0.1 in About but respond to requests using 1.0.3.

**Comment by garemoko** [comment]
I'm still arguing that the fact that the test requires the LRS only to support up to patch version 1.0.1 (and not 1.0.2 or 10.03) whilst sending requests declaring a version of 1.0.3 and providing links to spec version 1.0.3 is a bug, not a feature request. 

See https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#aboutresource

The LRS is only supposed to list the highest patch version of each minor version so if it includes 1.0.3, 1.0.2, 1.0.1  and 1.0.0 then that's incorrect behaviour.

**Comment by kylemoran** [comment]
The about test should be updated to check for the latest patch version which is 1.0.3

from the spec:

> An LRS MUST return the JSON document described above, with a "version" property that includes the latest minor and patch version the LRS conforms to, for each major version.
